# Generated by Django 3.0.8 on 2020-07-20 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uber', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=60)),
                ('avatar', models.ImageField(upload_to='ProfilePicture/')),
                ('contact_info', models.CharField(max_length=50)),
                ('current_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='uber.Location')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_pickup', to='uber.Location')),
            ],
        ),
    ]
